name: server_unit_tests
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "server/**/*"
jobs:
  server_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run unit tests
        run: echo "not implemented"